verbose: 1
types:
  block_content: {  }
  contact_message: {  }
  content_moderation_state: {  }
  entity_embed_fake_entity: {  }
  file: {  }
  media: {  }
  node:
    '*': '*'
  path_alias: {  }
  redirect: {  }
  search_api_task: {  }
  taxonomy_term: {  }
  user: {  }
  webform_submission: {  }
  menu_link_content: {  }
  paragraph: {  }
types_translation_lock: {  }
types_js_lock: {  }
form_op_lock:
  block_content:
    mode: 0
    values: {  }
  contact_message:
    mode: 0
    values: {  }
  content_moderation_state:
    mode: 1
    values: {  }
  entity_embed_fake_entity:
    mode: 0
    values: {  }
  file:
    mode: 0
    values: {  }
  media:
    mode: 1
    values: {  }
  node:
    mode: 0
    values:
      default: default
      delete: delete
      edit: edit
      delete-multiple-confirm: delete-multiple-confirm
  path_alias:
    mode: 0
    values: {  }
  redirect:
    mode: 0
    values: {  }
  search_api_task:
    mode: 0
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
  user:
    mode: 0
    values: {  }
  webform_submission:
    mode: 0
    values: {  }
  menu_link_content:
    mode: 0
    values: {  }
  paragraph:
    mode: 0
    values: {  }
_core:
  default_config_hash: 6Ka3T1c-CIjEUO1Q64NXKksLthkMhj53a6zy4RJBtkc
