unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: false
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: false
  contact_message_personal_form: false
  node_consultation_form: false
  node_feature_form: false
  node_featured_content_list_form: false
  node_news_form: false
  node_page_form: false
  node_publication_page_form: false
  node_staff_member_form: false
  node_vacancy_form: false
  node_webform_form: false
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
