features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
ga_tracking_disabled: 1
ga_tracking_disabled_eu: 1
