_core:
  default_config_hash: bltxRARtC357JTOCBWRowidH3hBn2IKOUHJIx9XsIwo
langcode: en
uuid: 98d9c1c3-f0a1-47b5-a39b-617f2ad4c19a
popup_enabled: true
popup_clicking_confirmation: false
popup_scrolling_confirmation: false
eu_only: false
eu_only_js: false
popup_position: false
fixed_top_position: false
popup_info:
  value: "<p>Cookies on the [site:name] website</p>\r\n\r\n<p>We use some essential cookies to make this service work. We'd like to set additional cookies so we can remember your settings, understand how people use the service and make improvements. Some of our pages allow selected third parties to set cookies - for example, pages that contain YouTube videos or Google Maps.</p>\r\n\r\n<p><a href=\"/cookies\">Find out more about how we use cookies</a></p>\r\n"
  format: basic_html
mobile_popup_info:
  value: ''
  format: basic_html
popup_info_template: new
popup_agree_button_message: 'Accept cookies'
popup_more_info_button_message: 'Find out more about how we use cookies'
mobile_breakpoint: 768
popup_agreed_enabled: false
popup_hide_agreed: false
disagree_button_label: 'Reject cookies'
popup_agreed:
  value: "<h2>Thank you for accepting cookies</h2>\r\n\r\n<p>You can now hide this message or find out more about cookies.</p>\r\n"
  format: basic_html
popup_find_more_button_message: 'More info'
popup_hide_button_message: Hide
popup_link: '<front>'
popup_link_new_window: true
popup_height: null
popup_width: ''
popup_delay: 300
show_more_info: false
popup_bg_hex: ''
popup_text_hex: ''
domain: ''
domains_option: 1
domains_list: .translate.goog
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
exclude_admin_theme: true
cookie_session: 0
set_cookie_session_zero_on_disagree: 0
cookie_lifetime: 365
use_mobile_message: false
use_bare_css: true
use_olivero_css: false
disagree_do_not_show_popup: false
reload_page: false
reload_options: 0
reload_routes_list: ''
cookie_name: ''
exclude_uid_1: true
better_support_for_screen_readers: true
method: opt_in
disabled_javascripts: ''
automatic_cookies_removal: true
allowed_cookies: ''
consent_storage_method: do_not_store
withdraw_message:
  value: "<p>Cookies on the [site:name] website</p>\r\n\r\n<p>You have given your consent for us to set additional cookies&nbsp;so we can remember your settings, understand how people use the service and make improvements.&nbsp; If you have changed your mind, you can withdraw consent.</p>\r\n\r\n<p><a href=\"/cookies\">Find out more about how we use cookies</a></p>\r\n"
  format: basic_html
withdraw_tab_button_label: 'Cookie settings'
withdraw_action_button_label: 'Withdraw consent'
withdraw_enabled: true
withdraw_button_on_info_popup: false
save_preferences_button_label: 'Save preferences'
accept_all_categories_button_label: 'Accept all cookies'
enable_save_preferences_button: true
domain_all_sites: false
settings_tab_enabled: true
containing_element: body
cookie_policy_version: 1.0.0
cookie_value_disagreed: '0'
cookie_value_agreed_show_thank_you: '1'
cookie_value_agreed: '2'
accessibility_focus: false
close_button_action: close_banner
reject_button_label: ''
reject_button_enabled: false
close_button_enabled: false
dependencies:
  config:
    - filter.format.basic_html
