_core:
  default_config_hash: U3bch6QlHy9RyVtqTqAjgLm3MI5tw4ODY3316QCZSzI
enabled: true
location: /app/log/ppsni
rotation:
  schedule: daily
  delete: true
  destination: 'archive/[date:custom:Y/m/d].log'
  gzip: true
format: "[[log:created:custom:'D, d/m/Y - H:i:s.000']] [[log:level]] [[log:channel]] [client: [log:ip], [log:user]] [log:message]"
level: 7
channels_type: exclude
channels: {  }
