blocks:
  -
    info: 'About the Public Prosecution Service'
    langcode: en
    uuid: 022a4599-345d-4609-a4db-3a989cafdeb1
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>The Public Prosecution Service (PPS) is the principal prosecuting authority in Northern Ireland, with responsibility for taking decisions as to prosecution in all cases investigated by the police. We also consider cases initiated or investigated by other statutory authorities, such as HM Revenue and Customs. We act impartially and in the interests of justice at all times, applying the highest professional standards and treating everyone fairly and with respect. We are at the heart of the criminal justice system and work with partners to build a safer community in which we respect the law and each other.</p>\r\n\r\n<p><a class=\"btn\" href=\"/about-pps\">More about us</a></p>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Twitter block'
    langcode: en
    uuid: d33e5b82-49b6-4792-b609-b5b2b9002fa1
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
  -
    info: 'How we work'
    langcode: en
    uuid: 0474ea51-31a9-4710-a70f-8fb732c16807
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h3><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"6c8c9932-4f49-4bab-9bde-f16c4b2ed546\" href=\"/node/20\">How we work</a></h3>\r\n\r\n<p>How prosecution decisions are made, alternatives to prosecution, prosecution guidance and how to request a review of a no prosecution decision</p>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Victim and Witness Information'
    langcode: en
    uuid: fbbec229-8750-45e7-b152-5d96994bc0ae
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h3><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"52176b26-5301-497a-9440-0643d9403948\" href=\"/node/18\">Victim and Witness Information</a></h3>\r\n\r\n<p>The prosecution process explained, advice on attending court and the services we provide to victims and witnesses</p>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Crime types'
    langcode: en
    uuid: e93001ed-4bad-4bf4-8143-f8f7215073c9
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h3><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"02c32c62-2a07-4f19-a0c4-6ac3b8b80394\" href=\"/node/19\">Crime types</a></h3>\r\n\r\n<p>Details of how the PPS handle specific crime times, including legacy cases and sexual offences</p>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Statistics and Research'
    langcode: en
    uuid: 49f709c0-3c03-4c04-b1ae-550af51b4f9f
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h3><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"1c0d63e0-d3e3-4744-a97f-0fa5141f5997\" href=\"/node/566\">Statistics and Research</a></h3>\r\n\r\n<p>Statistical information on key topic areas within the PPS, including files received, conviction rates, thematic bulletins, surveys and results.</p>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Contact Information'
    langcode: en
    uuid: 9628957b-46fa-4f2d-a3a7-103c6789096a
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h2>Contact Information</h2>\r\n\r\n<address>Public Prosecution Service</address>\r\n\r\n<address>Belfast Chambers</address>\r\n\r\n<address>93 Chichester Street</address>\r\n\r\n<address>Belfast</address>\r\n\r\n<address>BT1 3JR</address>\r\n\r\n<address>Email: <a href=\"mailto:info@ppsni-gov.uk\">info@ppsni.gov.uk</a></address>\r\n\r\n<address>Tel: +44 (0) 28 9089 7100</address>\r\n\r\n<p>&nbsp;</p>\r\n"
          summary: null
          format: full_html
  -
    info: 'Social links'
    langcode: en
    uuid: dd507b77-8aab-4cc9-81e1-8b48d4787c48
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
  -
    info: 'Footer logo'
    langcode: en
    uuid: 2e7428cf-d540-4ec4-ac16-f0bd30aebbaa
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<drupal-media data-align=\"center\" data-entity-type=\"media\" data-entity-uuid=\"09f1caa6-dda4-4607-8805-aeb6e17fe6ea\"></drupal-media>\r\n"
          summary: ''
          format: basic_html
menus:
  -
    menu_name: main
    title: Home
    parent: null
    uri: 'internal:/'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: 8c00b04f-29e3-46b8-976c-baf396450a56
  -
    menu_name: main
    title: 'About Us'
    parent: null
    uri: 'entity:node/8'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: und
    uuid: 475a4b08-e687-40c3-9d5f-71015060522f
  -
    menu_name: menu-footer-menu
    title: 'Access to information'
    parent: null
    uri: 'entity:node/2'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: 7c1c2b11-f208-4f6f-98eb-d0e5d4ed3f81
  -
    menu_name: menu-footer-menu
    title: 'Privacy policy'
    parent: null
    uri: 'entity:node/3'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: und
    uuid: 18186ddb-ec36-4f72-8184-392802874f12
  -
    menu_name: menu-footer-menu
    title: Accessibility
    parent: null
    uri: 'entity:node/4'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: und
    uuid: 064e053f-b4cf-4dbc-87ee-e96b5e4afe6b
  -
    menu_name: menu-footer-menu
    title: Cookies
    parent: null
    uri: 'entity:node/5'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: und
    uuid: 0a0a9862-2513-443a-a05c-882d6c5d87e6
  -
    menu_name: menu-footer-menu
    title: Disclaimer
    parent: null
    uri: 'entity:node/6'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -44
    langcode: und
    uuid: 43ba9702-27aa-4922-9669-bafa3b6e8bbf
  -
    menu_name: main
    title: 'Victims and Witnesses'
    parent: null
    uri: 'entity:node/18'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: und
    uuid: 6995ce53-8055-4702-8171-235c34c99ebc
  -
    menu_name: main
    title: 'How we work'
    parent: null
    uri: 'entity:node/20'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: und
    uuid: 9cbe7ea7-367f-4149-9c10-05c47cbf7a89
  -
    menu_name: main
    title: 'Crime types'
    parent: 'menu_link_content:9cbe7ea7-367f-4149-9c10-05c47cbf7a89'
    uri: 'entity:node/19'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: und
    uuid: b697a5c9-d551-4fe4-ade7-02b1176c1732
  -
    menu_name: main
    title: 'Prosecution guidance'
    parent: 'menu_link_content:9cbe7ea7-367f-4149-9c10-05c47cbf7a89'
    uri: 'entity:node/17'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -26
    langcode: und
    uuid: f768a1bf-cea5-413a-88df-b38fdbc33cfc
  -
    menu_name: main
    title: 'Domestic Violence'
    parent: 'menu_link_content:b697a5c9-d551-4fe4-ade7-02b1176c1732'
    uri: 'entity:node/63'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: 2475b1a1-4f64-417d-869b-6e94427b019c
  -
    menu_name: main
    title: Equality
    parent: 'menu_link_content:ae9b4044-91d9-4126-9940-b3aa98f6cb15'
    uri: 'entity:node/72'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 1
    langcode: und
    uuid: ed650738-684b-4142-b94d-50951f871552
  -
    menu_name: main
    title: 'From investigation to prosecution decision'
    parent: 'menu_link_content:6995ce53-8055-4702-8171-235c34c99ebc'
    uri: 'entity:node/289'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -6
    langcode: und
    uuid: 7e8d1096-a846-43e7-8ddf-44913a66e2b2
  -
    menu_name: main
    title: 'How we reach decisions'
    parent: 'menu_link_content:9cbe7ea7-367f-4149-9c10-05c47cbf7a89'
    uri: 'entity:node/290'
    link_title: null
    description: 'The Test for Prosecution'
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: 482d0a8c-6d50-459f-a424-2e3c147da488
  -
    menu_name: main
    title: 'Alternatives to prosecution'
    parent: 'menu_link_content:9cbe7ea7-367f-4149-9c10-05c47cbf7a89'
    uri: 'entity:node/292'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: und
    uuid: c9c68d28-b96b-41ad-98fd-4812cfc4676e
  -
    menu_name: main
    title: 'Senior Management Team'
    parent: 'menu_link_content:475a4b08-e687-40c3-9d5f-71015060522f'
    uri: 'entity:node/295'
    link_title: null
    description: 'Biographies of PPS senor management'
    enabled: true
    expanded: false
    weight: -7
    langcode: und
    uuid: 5a65a891-badc-4db3-8425-dbf606a84de3
  -
    menu_name: main
    title: 'Sexual offences'
    parent: 'menu_link_content:b697a5c9-d551-4fe4-ade7-02b1176c1732'
    uri: 'entity:node/301'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: 4127b52f-0f1e-4658-bc9d-4a99a9b0e184
  -
    menu_name: main
    title: 'Types of sexual offences'
    parent: 'menu_link_content:4127b52f-0f1e-4658-bc9d-4a99a9b0e184'
    uri: 'entity:node/302'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: eebb7ca0-3626-4e0c-983b-28f41f6c8ca0
  -
    menu_name: main
    title: 'Contact Us'
    parent: null
    uri: 'entity:node/55'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: 41bcca72-5e3d-48c1-a027-065ff09be402
  -
    menu_name: main
    title: 'The Victim and Witness Care Unit'
    parent: 'menu_link_content:6995ce53-8055-4702-8171-235c34c99ebc'
    uri: 'entity:node/404'
    link_title: null
    description: 'About the Victim and Witness Care Unit'
    enabled: true
    expanded: false
    weight: -36
    langcode: und
    uuid: d5b9d53c-f2a1-4dd6-a87a-bdad4770fd68
  -
    menu_name: main
    title: 'Attending court'
    parent: 'menu_link_content:6995ce53-8055-4702-8171-235c34c99ebc'
    uri: 'entity:node/406'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: und
    uuid: 1eefe3ed-a7e3-4925-be06-37080eecf512
  -
    menu_name: main
    title: 'Witness information'
    parent: 'menu_link_content:6995ce53-8055-4702-8171-235c34c99ebc'
    uri: 'entity:node/407'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 5
    langcode: und
    uuid: 40ffe95c-a4bb-498a-8c8c-77268307eb06
  -
    menu_name: main
    title: 'Hate Crime'
    parent: 'menu_link_content:b697a5c9-d551-4fe4-ade7-02b1176c1732'
    uri: 'entity:node/409'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 17
    langcode: und
    uuid: 638fffd6-46f9-4b8f-804d-6caaeefaa73e
  -
    menu_name: main
    title: 'Types of Hate Crime'
    parent: 'menu_link_content:638fffd6-46f9-4b8f-804d-6caaeefaa73e'
    uri: 'entity:node/412'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: df7b2047-dbbb-4cfc-a713-e2f054d89fbb
  -
    menu_name: main
    title: 'Requesting a review'
    parent: 'menu_link_content:9cbe7ea7-367f-4149-9c10-05c47cbf7a89'
    uri: 'entity:node/418'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -2
    langcode: und
    uuid: 26d7081b-9ab1-4d0b-b830-b1a7a81d02d7
  -
    menu_name: main
    title: 'Complaints and Feedback'
    parent: 'menu_link_content:9cbe7ea7-367f-4149-9c10-05c47cbf7a89'
    uri: 'entity:node/422'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -1
    langcode: und
    uuid: bc78905e-7ac5-4293-9f4c-e6f708640eaf
  -
    menu_name: main
    title: 'Independent Assessor of Complaints'
    parent: 'menu_link_content:bc78905e-7ac5-4293-9f4c-e6f708640eaf'
    uri: 'entity:node/424'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: ba562049-a36f-44f1-b0bc-680e8dc8879f
  -
    menu_name: main
    title: 'Special Measures'
    parent: 'menu_link_content:6995ce53-8055-4702-8171-235c34c99ebc'
    uri: 'entity:node/427'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: und
    uuid: ea448fce-aaa0-4e03-a835-cea2c31c9232
  -
    menu_name: main
    title: 'The Gillen Review'
    parent: 'menu_link_content:4127b52f-0f1e-4658-bc9d-4a99a9b0e184'
    uri: 'entity:node/430'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 4
    langcode: und
    uuid: 4217cfef-a4a6-44ce-a85c-26c41a198765
  -
    menu_name: main
    title: 'Our statutory duties'
    parent: 'menu_link_content:9cbe7ea7-367f-4149-9c10-05c47cbf7a89'
    uri: 'entity:node/431'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: dedda9f2-cf9e-43ba-9c18-6dca11809412
  -
    menu_name: main
    title: 'Unduly lenient sentences'
    parent: 'menu_link_content:9cbe7ea7-367f-4149-9c10-05c47cbf7a89'
    uri: 'entity:node/433'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 1
    langcode: und
    uuid: 3c525dc3-2514-4a7e-ab42-4575b286d1f5
  -
    menu_name: main
    title: 'Legal terms explained'
    parent: 'menu_link_content:6995ce53-8055-4702-8171-235c34c99ebc'
    uri: 'entity:node/439'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 1
    langcode: und
    uuid: 35dfb6e9-a9ef-4e03-bf04-f0948a6c7580
  -
    menu_name: main
    title: 'Road Traffic offences'
    parent: 'menu_link_content:b697a5c9-d551-4fe4-ade7-02b1176c1732'
    uri: 'entity:node/413'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -6
    langcode: und
    uuid: 6a685ef3-31a1-4d67-ae2f-a92b8d63ba36
  -
    menu_name: main
    title: 'Corporate Governance'
    parent: 'menu_link_content:475a4b08-e687-40c3-9d5f-71015060522f'
    uri: 'entity:node/518'
    link_title: null
    description: 'PPS Corporate governance arrangements'
    enabled: true
    expanded: false
    weight: -1
    langcode: und
    uuid: ae9b4044-91d9-4126-9940-b3aa98f6cb15
  -
    menu_name: main
    title: 'Vulnerable or Intimidated witnesses'
    parent: 'menu_link_content:6995ce53-8055-4702-8171-235c34c99ebc'
    uri: 'entity:node/543'
    link_title: null
    description: 'Information on services available to vulnerable or intimated witnesses, including who is eligible to claim witness expenses'
    enabled: true
    expanded: false
    weight: -47
    langcode: und
    uuid: d24c9eab-d55b-462a-a819-e68660543953
  -
    menu_name: main
    title: 'Witness Expenses'
    parent: 'menu_link_content:6995ce53-8055-4702-8171-235c34c99ebc'
    uri: 'entity:node/542'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -28
    langcode: und
    uuid: 6b37d35a-e80f-4384-8f07-dc7f1824c87a
  -
    menu_name: main
    title: 'Our Structure'
    parent: 'menu_link_content:475a4b08-e687-40c3-9d5f-71015060522f'
    uri: 'entity:node/135'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -10
    langcode: und
    uuid: 049ffe7b-0c1a-4684-a8d4-39a10713694e
  -
    menu_name: main
    title: 'The Prosecution Process'
    parent: 'menu_link_content:6995ce53-8055-4702-8171-235c34c99ebc'
    uri: 'entity:node/548'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: 38ca4a83-33c4-4475-aa80-08439b3d298d
  -
    menu_name: main
    title: 'Quality Standards'
    parent: 'menu_link_content:9cbe7ea7-367f-4149-9c10-05c47cbf7a89'
    uri: 'entity:node/556'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 50
    langcode: und
    uuid: c4bf9771-8468-48b5-ac2d-2fd4f3a00f80
  -
    menu_name: main
    title: 'Hate Crime video'
    parent: 'menu_link_content:638fffd6-46f9-4b8f-804d-6caaeefaa73e'
    uri: 'entity:node/560'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: 13088daf-0cd5-484f-994b-9212eabee824
  -
    menu_name: main
    title: 'Covid-19: Notice for defence practitioners'
    parent: 'menu_link_content:9cbe7ea7-367f-4149-9c10-05c47cbf7a89'
    uri: 'entity:node/619'
    link_title: null
    description: 'How to contact the PPS during the Covid-19 pandemic'
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: 8385833d-1e0c-453a-abe7-723541bc3a95
