_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: bb61a33e-a669-4339-89fc-99bc57c8995a
name: 'Public Prosecution Service NI'
mail: info@ppsni.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Public Prosecution Service NI'
frontpage_show_title: 0
