_core:
  default_config_hash: bltxRARtC357JTOCBWRowidH3hBn2IKOUHJIx9XsIwo
langcode: en
uuid: 006beffc-28e5-4581-a14b-a96363d53aa2
popup_enabled: true
popup_clicking_confirmation: false
popup_scrolling_confirmation: false
eu_only: null
eu_only_js: null
popup_position: true
fixed_top_position: false
popup_info:
  value: '<h2>We use cookies on this site to enhance your user experience</h2><p>By clicking the Accept button, you agree to us doing so.</p>'
  format: basic_html
mobile_popup_info:
  value: '<h2>We use cookies on this site to enhance your user experience</h2><p>By tapping the Accept button, you agree to us doing so.</p>'
  format: basic_html
popup_info_template: new
popup_agree_button_message: Accept
popup_more_info_button_message: 'More info'
mobile_breakpoint: 768
popup_agreed_enabled: false
popup_hide_agreed: false
disagree_button_label: 'No, thanks'
popup_agreed:
  value: '<h2>Thank you for accepting cookies</h2><p>You can now hide this message or find out more about cookies.</p>'
  format: basic_html
popup_find_more_button_message: 'More info'
popup_hide_button_message: Hide
popup_link: '<front>'
popup_link_new_window: true
popup_height: null
popup_width: ''
popup_delay: 1000
show_more_info: false
popup_bg_hex: ''
popup_text_hex: ''
domain: ''
domains_option: 1
domains_list: ''
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
exclude_admin_theme: false
cookie_session: 0
set_cookie_session_zero_on_disagree: 0
cookie_lifetime: 365
use_mobile_message: false
use_bare_css: true
disagree_do_not_show_popup: false
reload_page: true
reload_options: 0
reload_routes_list: ''
cookie_name: ''
exclude_uid_1: false
better_support_for_screen_readers: true
method: opt_in
disabled_javascripts: ''
automatic_cookies_removal: false
allowed_cookies: ''
consent_storage_method: do_not_store
withdraw_message:
  value: '<h2>We use cookies on this site to enhance your user experience</h2><p>You have given your consent for us to set cookies.</p>'
  format: basic_html
withdraw_tab_button_label: 'Privacy settings'
withdraw_action_button_label: 'Withdraw consent'
withdraw_enabled: false
withdraw_button_on_info_popup: false
save_preferences_button_label: 'Save preferences'
accept_all_categories_button_label: 'Accept all cookies'
enable_save_preferences_button: true
domain_all_sites: false
settings_tab_enabled: false
containing_element: body
cookie_policy_version: 1.0.0
