_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - 'ircommission_theme.settings:twitter_profile_url'
  - 'ircommission_theme.settings:facebook_profile_url'
  - 'ircommission_theme.settings:linkedin_profile_url'
  - 'ircommission_theme.settings:pinterest_profile_url'
  - 'ircommission_theme.settings:youtube_profile_url'
  - 'ircommission_theme.settings:instagram_profile_url'
