blocks:
  -
    info: 'About IRC block'
    langcode: en
    uuid: d9ff9dd7-616f-4759-b541-c1fe28585240
    bundle: about_irc_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>The Independent Reporting Commission (IRC) was created under the Fresh Start Agreement, to monitor progress on tackling paramilitary activity in Northern Ireland.</p>\r\n"
          summary: ''
          format: full_html
