_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 285e4ec3-0671-4e67-8816-312c3ed435e9
name: 'Independent Reporting Commission'
mail: admin@ircommission.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/56
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Drupal site'
frontpage_show_title: 0
