_core:
  default_config_hash: g1xKHKD8msGv9RR5tnTxVhqTCkof96Cd4KF4mOLEntI
report-only:
  enable: true
  directives:
    default-src:
      base: self
    connect-src:
      base: self
      sources:
        - 'https://www.google-analytics.com'
    font-src:
      base: self
      sources:
        - 'https://themes.googleusercontent.com'
        - 'https://fonts.gstatic.com'
        - 'https://use.fontawesome.com'
        - 'https://cdn.jsdelivr.net'
        - 'data:'
    frame-src:
      base: self
      sources:
        - 'https://www.youtube.com'
        - 'https://twitter.com'
        - platform.twitter.com
        - syndication.twitter.com
    img-src:
      base: self
      sources:
        - 'https://translate.google.com'
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - 'https://cdn.jsdelivr.net'
        - 'https://i.ytimg.com'
        - 'https://www.gstatic.com'
        - 'https://maps.gstatic.com'
        - 'https://maps.googleapis.com'
        - 'data:'
        - abs.twimg.com
        - 'https://pbs.twimg.com'
        - ton.twimg.com
        - platform.twitter.com
        - 'https://syndication.twitter.com'
    manifest-src:
      base: self
    script-src:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - 'https://cdn.syndication.twimg.com'
        - api.twitter.com
        - platform.twitter.com
    script-src-attr:
      base: self
    script-src-elem:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - 'https://cdn.syndication.twimg.com'
        - api.twitter.com
        - platform.twitter.com
    style-src:
      base: self
      flags:
        - unsafe-inline
      sources:
        - 'https://ton.twimg.com'
        - platform.twitter.com
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
      sources:
        - 'https://ton.twimg.com'
        - platform.twitter.com
    block-all-mixed-content: true
  reporting:
    plugin: sitelog
enforce:
  enable: false
  directives:
    default-src:
      base: self
    font-src:
      base: self
      sources:
        - 'https://themes.googleusercontent.com'
        - 'https://fonts.gstatic.com'
        - 'https://use.fontawesome.com'
        - 'https://cdn.jsdelivr.net'
        - 'data:'
    frame-src:
      base: self
      sources:
        - 'https://www.youtube.com'
    img-src:
      base: self
      sources:
        - 'https://cdn.jsdelivr.net'
        - 'https://i.ytimg.com'
        - 'https://maps.gstatic.com'
        - 'https://maps.googleapis.com'
        - 'data:'
    script-src:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
    script-src-elem:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
    style-src:
      base: self
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
    block-all-mixed-content: true
  reporting:
    plugin: sitelog
