_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  automated_cron: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  content_lock: 0
  content_lock_timeout: 0
  content_moderation: 0
  contextual: 0
  cookie_content_blocker: 0
  csp: 0
  ctools: 0
  date_facet_drilldown: 0
  datetime: 0
  datetime_range: 0
  diff: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  facets: 0
  facets_pretty_paths: 0
  facets_summary: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filelog: 0
  filter: 0
  flag: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geolocation: 0
  geolocation_google_maps: 0
  geolocation_google_static_maps: 0
  google_analytics: 0
  handy_cache_tags: 0
  help: 0
  history: 0
  honeypot: 0
  http_cache_control: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  link_fix_absolute_urls: 0
  linkit: 0
  media: 0
  media_library: 0
  media_library_edit: 0
  menu_breadcrumb: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  moderation_sidebar: 0
  node: 0
  node_edit_protection: 0
  noreferrer: 0
  options: 0
  origins_ckeditor_enhancements: 0
  origins_common: 0
  origins_media: 0
  origins_metatag: 0
  origins_qa: 0
  origins_toc: 0
  origins_unique_title: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rdf: 0
  redirect: 0
  redis: 0
  responsive_image: 0
  scheduled_transitions: 0
  search: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_location: 0
  search_api_location_views: 0
  search_api_solr: 0
  search_api_spellcheck: 0
  simplei: 0
  structure_sync: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  twig_tweak: 0
  ultimate_cron: 0
  unity_common: 0
  unity_frontpage: 0
  unity_image_styles: 0
  unity_internal_link_checker: 0
  unity_map_embed: 0
  unity_search_pages: 0
  update: 0
  user: 0
  views_custom_cache_tag: 0
  webform: 0
  webform_access: 0
  webform_node: 0
  webform_ui: 0
  whatlinkshere: 0
  workflows: 0
  menu_admin_per_menu: 1
  pathauto: 1
  origins_workflow: 2
  views: 10
  paragraphs: 11
  nicsdru_unity_profile: 1000
  readonlymode: 9999
  eu_cookie_compliance: 10000
theme:
  stark: 0
  seven: 0
  stable: 0
  adminimal_theme: 0
  nicsdru_unity_theme: 0
  victimspaymentsboard_theme: 0
profile: nicsdru_unity_profile
