blocks:
  -
    info: 'Homepage Application'
    langcode: en
    uuid: 35cd7b6a-cb9c-4988-9dee-24be3f5cb306
    bundle: link_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><img alt=\"making an application\" data-delta=\"4\" data-fid=\"20\" data-media-element=\"1\" height=\"140\" src=\"https://www.victimspaymentsboard.org.uk/sites/victimspayments/files/media-files/making-an-application.png\" width=\"220\" /></p>\r\n\r\n<p>Making an application</p>\r\n"
          summary: ''
          format: full_html
      field_link:
        -
          uri: 'internal:/node/36'
          title: ''
          options: {  }
  -
    info: 'Homepage Guidance'
    langcode: en
    uuid: 2534d391-4cfd-45b0-a985-c4161d419e70
    bundle: link_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><img alt=\"Guidance for applicants\" data-delta=\"4\" data-fid=\"19\" data-media-element=\"1\" src=\"https://www.victimspaymentsboard.org.uk/sites/victimspayments/files/media-files/guidance-applicants.png\" /></p>\r\n\r\n<p>Guidance to applicants</p>\r\n"
          summary: ''
          format: full_html
      field_link:
        -
          uri: 'internal:/node/19'
          title: ''
          options: {  }
  -
    info: 'Homepage Support'
    langcode: en
    uuid: d7d316c2-19e8-4638-8273-0f159d0ff113
    bundle: link_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><img alt=\"Support services\" data-delta=\"4\" data-fid=\"21\" data-media-element=\"1\" src=\"https://www.victimspaymentsboard.org.uk/sites/victimspayments/files/media-files/support-services.png\" /></p>\r\n\r\n<p>Support Services</p>\r\n"
          summary: ''
          format: full_html
      field_link:
        -
          uri: 'internal:/support-services-0'
          title: ''
          options: {  }
  -
    info: 'Homepage Contact us'
    langcode: en
    uuid: 6d009f83-80b5-463b-906b-c34997329338
    bundle: link_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><img alt=\"Contact us\" data-delta=\"4\" data-fid=\"22\" data-media-element=\"1\" src=\"https://www.victimspaymentsboard.org.uk/sites/victimspayments/files/media-files/contact-us.png\" /></p>\r\n\r\n<p>Contact us</p>\r\n"
          summary: ''
          format: full_html
      field_link:
        -
          uri: 'entity:node/34'
          title: ''
          options: {  }
  -
    info: 'Homepage Troubles info block'
    langcode: en
    uuid: 131f6977-0feb-41d5-8ab2-2b864c3d176c
    bundle: basic
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<p>The Victims’ Payments Board was established in February 2021. The Board is headed by a President appointed by the Lord Chief Justice, and will consist of a number of members including legal, medical and ordinary members. The purpose of the Board is to determine applications under the Troubles Permanent Disablement Payment Scheme (also referred to as the Victims’ Payments Scheme). Members will also have responsibility as members of the Victims’ Payments Board to assist the President with corporate governance responsibilities such as policy development, financial and risk management.&nbsp;</p><p><a class="btn" href="/node/9">Read more</a></p><p>We are currently experiencing delays in answering calls to the VPB contact number. We appreciate your patience in this matter. Please be advised, you can also contact us by emailing <a href="mailto:vpb@justice-ni.gov.uk">vpb@justice-ni.gov.uk</a></p><p>Applicants to the Scheme are reminded that it is not necessary to seek additional information from Health Trusts, GPs, Police, PRONI, etc in support of their application – this is because the Victims’ Payments Board has arrangements in place to formally request this information, as required. We will however require the basic details requested on the application form to include incident date, location and description.</p><p class="info-notice">When submitting an application to the Scheme, applicants should only include supporting information they currently hold.</p>'
          summary: null
          format: filtered_html
menus:
  -
    menu_name: main
    title: Home
    parent: null
    uri: 'internal:/'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: c3c9d7cb-c41b-4e3d-aa70-4b803f588c9c
  -
    menu_name: main
    title: 'About Us'
    parent: null
    uri: 'entity:node/51'
    link_title: ''
    description: null
    enabled: true
    expanded: true
    weight: -49
    langcode: en
    uuid: 25d06bcc-9d2b-44b9-a8df-4eda4bee48e9
  -
    menu_name: main
    title: Statistics
    parent: 'menu_link_content:25d06bcc-9d2b-44b9-a8df-4eda4bee48e9'
    uri: 'entity:node/50'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: en
    uuid: ad164f33-5c12-4a3b-99ed-1911d509a6b5
  -
    menu_name: main
    title: Regulations
    parent: 'menu_link_content:25d06bcc-9d2b-44b9-a8df-4eda4bee48e9'
    uri: 'entity:node/8'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: en
    uuid: cc77209f-ef37-4d83-bfc8-f1c0f8fa4ba1
  -
    menu_name: main
    title: 'Guidance to Applicants'
    parent: null
    uri: 'internal:/guidance-applicants-0'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: en
    uuid: a1131e04-8f52-4b59-b622-a415d1aad5f4
  -
    menu_name: main
    title: 'Making an Application'
    parent: null
    uri: 'entity:node/36'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: en
    uuid: 61b3c02f-1177-41ec-86b9-aed2c27fb7c3
  -
    menu_name: main
    title: 'Support Services'
    parent: null
    uri: 'entity:node/3'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: en
    uuid: 6cfb50f4-9f48-4c32-9e26-63b6fd10f89c
  -
    menu_name: main
    title: 'Contact Us'
    parent: null
    uri: 'entity:node/34'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -43
    langcode: en
    uuid: f993ff3c-6b38-4b22-9b99-1034ceff13ed
  -
    menu_name: menu-footer-links
    title: '© Crown Copyright'
    parent: null
    uri: 'entity:node/5'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: en
    uuid: bc3addd1-d0cd-4535-a360-b879da5eb005
  -
    menu_name: menu-footer-links
    title: 'Accessibility Statement'
    parent: null
    uri: 'entity:node/7'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: en
    uuid: 36b8ec9a-5503-4042-a021-e4bb71569442
  -
    menu_name: menu-footer-links
    title: Cookies
    parent: null
    uri: 'entity:node/6'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: en
    uuid: 2a49280d-698d-4286-9e17-647b5d0d1c31
  -
    menu_name: main
    title: Publications
    parent: null
    uri: 'internal:/Publications'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: en
    uuid: 060ace61-ab8a-431d-a338-ffeb16806c8c
  -
    menu_name: main
    title: FAQ
    parent: null
    uri: 'entity:node/73'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -44
    langcode: en
    uuid: 9a645bfc-90a7-44f7-9905-69ab6cdd873e
