_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: a9526ead-559e-4920-9f06-0ae86b26bd04
name: 'Victims'' Payments Board'
mail: vpb@justice-ni.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/74
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Victims Payments Board'
frontpage_show_title: 0
