_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
name: 'Victims Payments Board'
mail: victimspaymentsboard@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
uuid: a9526ead-559e-4920-9f06-0ae86b26bd04
frontpage_title: 'Welcome to Drupal site'
