<?php

/**
 * @file
 * Functions to support theming in the IR Commission.
 */

function ircommission_theme_theme_suggestions_container_alter(array &$suggestions, array $variables)
{
  $name = '';
  $type = '';
  if (isset($variables['element']['#name'])) {
    $name = $variables['element']['#name'];
  }

  if (isset($variables['element']['#type'])) {
    $type = $variables['element']['#type'];
  }

  array_unshift($suggestions, 'container__' . $type . '__' . $name);
}
