_core:
  default_config_hash: 4JpC3F2x_VsACQQuTI4JOMCLDQcjUp0gTMJspJQ2M7s
report-only:
  enable: true
  directives:
    default-src:
      base: self
    connect-src:
      base: self
      sources:
        - 'https://www.google-analytics.com'
        - 'https://region1.google-analytics.com'
        - 'https://*.twitter.com'
    font-src:
      base: self
      sources:
        - 'https://themes.googleusercontent.com'
        - 'https://fonts.gstatic.com'
        - 'https://use.fontawesome.com'
        - 'https://cdn.jsdelivr.net'
        - 'data:'
        - '*.typekit.com'
    frame-src:
      base: self
      sources:
        - 'https://www.youtube.com'
        - 'https://*.twitter.com'
    img-src:
      base: self
      sources:
        - 'https://translate.google.com'
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - 'https://cdn.jsdelivr.net'
        - 'https://i.ytimg.com'
        - 'https://www.gstatic.com'
        - 'https://maps.gstatic.com'
        - 'https://maps.googleapis.com'
        - 'data:'
        - 'https://*.twitter.com'
    manifest-src:
      base: self
    script-src:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - 'https://*.twitter.com'
    script-src-attr:
      base: self
    script-src-elem:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - 'https://*.twitter.com'
    style-src:
      base: self
      sources:
        - '*.typekit.com'
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
    block-all-mixed-content: true
  reporting:
    plugin: none
enforce:
  enable: false
  directives:
    default-src:
      base: self
    font-src:
      base: self
      sources:
        - 'https://themes.googleusercontent.com'
        - 'https://fonts.gstatic.com'
        - 'https://use.fontawesome.com'
        - 'https://cdn.jsdelivr.net'
        - 'data:'
    frame-src:
      base: self
      sources:
        - 'https://www.youtube.com'
    img-src:
      base: self
      sources:
        - 'https://cdn.jsdelivr.net'
        - 'https://i.ytimg.com'
        - 'https://maps.gstatic.com'
        - 'https://maps.googleapis.com'
        - 'data:'
    script-src:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
    script-src-elem:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
    style-src:
      base: self
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
    block-all-mixed-content: true
  reporting:
    plugin: sitelog
