plugins:
  - cleanupAttrs: true
  - inlineStyles: true
  - removeStyleElement: true
  - removeComments: true
  - removeMetadata: true
  - removeTitle: true
  - removeDesc: true
  - removeUselessDefs: true
  - removeDimensions: true
  - removeRasterImages: true
  - collapseGroups: true
  - cleanupNumericValues: { floatPrecision: 1 }
  - cleanupIDs: true
  - removeEmptyContainers: true
  - removeEmptyAttrs: true
  - cleanupAttrs: true
  - removeAttrs: { attrs: ‘(class|id|data-name)’ }
