blocks:
  -
    info: Welcome
    langcode: en
    uuid: 3b622c47-1d21-4909-a88a-2ffac68e1311
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h1>Welcome from the Commissioner Designate for Victims of Crime</h1>\r\n\r\n<drupal-media data-align=\"center\" data-entity-type=\"media\" data-entity-uuid=\"b48a0788-bc7d-4698-aff9-4df8ea504a7a\" data-view-mode=\"\"></drupal-media>\r\n"
          summary: ''
          format: full_html
  -
    info: 'Homepage victim charter'
    langcode: en
    uuid: e611ad05-0056-4ef9-a135-55ee3793da15
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<drupal-media data-align=\"center\" data-entity-type=\"media\" data-entity-uuid=\"3ed01e1f-a482-4f8a-a927-1f7e669cbed9\"></drupal-media>\r\n\r\n<p><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"faf70d5f-6bc5-4b18-919e-96a718589793\" href=\"/node/16\">Victim Charter&nbsp;</a></p>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Homepage how to complain'
    langcode: en
    uuid: 51aad198-6ff6-4ca4-ac34-f9b6b2c253a1
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<drupal-media data-align=\"center\" data-entity-type=\"media\" data-entity-uuid=\"9aadf172-3c61-454e-9bf6-6caa334b263c\"></drupal-media>\r\n\r\n<p><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"1314e32a-4f55-402e-8d5f-ef37a05cd152\" href=\"/node/19\">How to Complain&nbsp;</a></p>\r\n"
          summary: null
          format: full_html
  -
    info: 'Homepage Victim Survey'
    langcode: en
    uuid: d52fe534-3c51-4481-9861-b90e669d8403
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<drupal-media data-align=\"center\" data-entity-type=\"media\" data-entity-uuid=\"ed8ae9e5-5a57-42ec-8934-eab2fa3ccb72\"></drupal-media>\r\n\r\n<p><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"c36765a1-204e-4f3e-b23c-89f91b3b19c5\" href=\"/node/24\">Victim Survey&nbsp;</a></p>\r\n"
          summary: null
          format: full_html
  -
    info: 'Twitter block'
    langcode: en
    uuid: cb5ff9c6-c76b-4650-ab70-32823dc3069f
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
menus:
  -
    menu_name: main
    title: Home
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: en
    uuid: ec85a6a8-716b-4c6b-9b5c-611d7bca8eb3
  -
    menu_name: main
    title: 'What we do'
    parent: null
    uri: 'entity:node/6'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: en
    uuid: 113ba397-5db5-40d0-b1c7-f01dccb38cbf
  -
    menu_name: main
    title: 'Contact Us'
    parent: null
    uri: 'internal:/contact-us'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -43
    langcode: en
    uuid: 645fb80a-daa0-4449-9252-5281abe72208
  -
    menu_name: main
    title: 'Who we are'
    parent: null
    uri: 'entity:node/5'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: en
    uuid: 4117bce1-19c4-4c98-a195-8619ff80ba00
  -
    menu_name: main
    title: 'Help us to help others'
    parent: null
    uri: 'entity:node/7'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: en
    uuid: 28d80f35-1eb1-4554-b6c4-7ed14ab38d92
  -
    menu_name: main
    title: 'Help for you'
    parent: null
    uri: 'entity:node/8'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: en
    uuid: 4c40ff79-2f60-4274-9057-3d0c1de32f39
  -
    menu_name: main
    title: 'Role of the Commissioner Designate'
    parent: 'menu_link_content:4117bce1-19c4-4c98-a195-8619ff80ba00'
    uri: 'entity:node/12'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: 12ca3ff9-ac95-47ba-ba36-f80e1147d67a
  -
    menu_name: main
    title: 'Commissioner Designate'
    parent: 'menu_link_content:4117bce1-19c4-4c98-a195-8619ff80ba00'
    uri: 'entity:node/13'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: 178cb21c-ea2c-496f-b6d9-f2975b745766
  -
    menu_name: main
    title: 'Our Team'
    parent: 'menu_link_content:4117bce1-19c4-4c98-a195-8619ff80ba00'
    uri: 'entity:node/14'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: 67e82c4e-5985-4fa5-9bf9-96f13bad6194
  -
    menu_name: main
    title: 'Criminal Justice Journey'
    parent: 'menu_link_content:4c40ff79-2f60-4274-9057-3d0c1de32f39'
    uri: 'entity:node/15'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: aff0b426-b5de-40d9-ae7a-1ca7445e3d80
  -
    menu_name: main
    title: 'Victim Charter'
    parent: 'menu_link_content:4c40ff79-2f60-4274-9057-3d0c1de32f39'
    uri: 'entity:node/16'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: 3fbafa2d-bf4b-4781-8514-a4794ddc16f5
  -
    menu_name: main
    title: 'Witness Charter'
    parent: 'menu_link_content:4c40ff79-2f60-4274-9057-3d0c1de32f39'
    uri: 'entity:node/17'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: fbdb07fc-954e-4590-8021-3f525fa45165
  -
    menu_name: main
    title: 'Useful Organisations'
    parent: 'menu_link_content:4c40ff79-2f60-4274-9057-3d0c1de32f39'
    uri: 'entity:node/18'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: fda9b1d8-78df-4b0b-9fb9-bf6cc14e71c6
  -
    menu_name: main
    title: 'Make a Complaint'
    parent: 'menu_link_content:4c40ff79-2f60-4274-9057-3d0c1de32f39'
    uri: 'entity:node/19'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: 0ba415f5-5166-4f73-91d9-fef78af3485c
  -
    menu_name: main
    title: 'Cover your tracks'
    parent: 'menu_link_content:4c40ff79-2f60-4274-9057-3d0c1de32f39'
    uri: 'entity:node/20'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: c1f0b9fd-3ccc-4e82-9269-86a48e5d0a7e
  -
    menu_name: menu-footer-links
    title: '© Crown Copyright'
    parent: null
    uri: 'entity:node/21'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: en
    uuid: dd9db56c-2db1-4959-94b8-3e4c80ce7e31
  -
    menu_name: menu-footer-links
    title: Cookies
    parent: null
    uri: 'entity:node/22'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: en
    uuid: 4a7babbb-5134-4651-8c5b-ca2c28862b88
  -
    menu_name: menu-footer-links
    title: 'Accessibility Statement'
    parent: null
    uri: 'entity:node/23'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: en
    uuid: 9f3a3349-6a3b-44e4-b016-b080f78c92bf
taxonomies:
  landing_pages_contact_card_colou: {  }
  publication_type:
    -
      vid: publication_type
      tid: '1'
      langcode: en
      name: 'Test type 1'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 0c8b88a8-65b1-4d34-b23a-5992d1d37c38
    -
      vid: publication_type
      tid: '2'
      langcode: en
      name: 'Test type 2'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: ffdb7e4c-3534-4352-b5d4-950cb4f22e99
    -
      vid: publication_type
      tid: '3'
      langcode: en
      name: 'Test type 3'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 67c1396a-b326-489c-9f3f-fa3c202725c7
  site_topics: {  }
  tags: {  }
