_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - 'hiaredressni_theme.settings:twitter_profile_url'
  - 'hiaredressni_theme.settings:facebook_profile_url'
  - 'hiaredressni_theme.settings:linkedin_profile_url'
  - 'hiaredressni_theme.settings:pinterest_profile_url'
  - 'hiaredressni_theme.settings:youtube_profile_url'
  - 'hiaredressni_theme.settings:instagram_profile_url'
  - 'hiaredressni_theme.settings:basic_page_structure'
  - block.block.sociallinks
