_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
name: 'HIA Redress Board'
mail: admin@hiaredressni.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
uuid: 039d7cd2-7af3-44f9-a236-509475faf0bb
frontpage_title: 'Welcome to Drupal site'
