_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 039d7cd2-7af3-44f9-a236-509475faf0bb
name: 'HIA Redress Board'
mail: admin@hiaredressni.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'HIA Redress Board'
frontpage_show_title: 0
