_core:
  default_config_hash: bDFGUgtLFi78q8mKcex_zI95jAXkkm_alGhixx2giXA
mirror_operations:
  'view scheduled transition': update
  'add scheduled transition': update
  'reschedule scheduled transitions': update
automation:
  cron_create_queue_items: true
bundles:
  -
    entity_type: node
    bundle: basic_page
  -
    entity_type: node
    bundle: core_funded_groups
  -
    entity_type: node
    bundle: event
  -
    entity_type: node
    bundle: featured_list
  -
    entity_type: node
    bundle: funding_schemes
  -
    entity_type: node
    bundle: news
  -
    entity_type: node
    bundle: project_profile
  -
    entity_type: node
    bundle: publication
  -
    entity_type: node
    bundle: staff_member
  -
    entity_type: node
    bundle: webform
message_transition_latest: 'Scheduled transition: transitioning latest revision from [scheduled-transitions:from-state] to [scheduled-transitions:to-state]'
message_transition_historical: 'Scheduled transition: copied revision #[scheduled-transitions:from-revision-id] and changed from [scheduled-transitions:from-state] to [scheduled-transitions:to-state]'
message_transition_copy_latest_draft: 'Scheduled transition: reverted [scheduled-transitions:latest-state] revision #[scheduled-transitions:latest-revision-id] back to top'
message_override: false
