blocks:
  -
    info: 'Funding Map'
    langcode: en
    uuid: 0640f73c-379c-49c9-b23d-a2f7f76250b9
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><iframe height=\"480\" src=\"https://www.google.com/maps/d/embed?mid=1WaeHi2cMM1u9ACbqHmhUJjVb8AZm0R73\" width=\"640\"></iframe></p>\r\n\r\n<p><a href=\"/funding-map-archive\">See previous funding maps here</a></p>\r\n"
          summary: null
          format: full_html
  -
    info: 'Funding Map Archive'
    langcode: en
    uuid: f79e06d2-06a6-4c56-ba0c-ff5cbe06f834
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<iframe src="https://www.google.com/maps/d/embed?mid=1uuGu5yOclN1YhkvjAW08sUKM2dIn-H05&ehbc=2E312F" width="640" height="480"></iframe>'
          summary: ''
          format: full_html
menus:
  -
    menu_name: main
    title: Home
    parent: null
    uri: 'internal:/'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: 6f613c66-44f6-4271-a0cf-ab79b0062586
  -
    menu_name: menu-footer-menu
    title: Links
    parent: null
    uri: 'entity:node/75'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: 33ecd898-322a-4024-ae23-398e43c8007c
  -
    menu_name: menu-footer-menu
    title: Accessibility
    parent: null
    uri: 'entity:node/76'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: und
    uuid: dd02825a-cfa2-4b06-88a9-add08b338e2c
  -
    menu_name: menu-footer-menu
    title: Disclaimer
    parent: null
    uri: 'entity:node/77'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: und
    uuid: 072f1356-3ac4-4334-9f3c-3aadfc1d3f2a
  -
    menu_name: menu-footer-menu
    title: 'Freedom of Information'
    parent: null
    uri: 'entity:node/78'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: und
    uuid: 6b220317-1256-4e1f-880c-457da1fd068f
  -
    menu_name: main
    title: Funding
    parent: null
    uri: 'entity:node/79'
    link_title: ''
    description: 'CRC Funding'
    enabled: true
    expanded: false
    weight: -43
    langcode: und
    uuid: 6d849f82-58f7-4dba-9cb5-fc2105b15f96
  -
    menu_name: menu-footer-menu
    title: Cookies
    parent: null
    uri: 'entity:node/221'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: und
    uuid: 1b4e392a-e925-449a-91cc-a72fa974d8c2
  -
    menu_name: main
    title: 'Corporate Policies'
    parent: 'menu_link_content:a2bd328e-aa96-49fd-83da-d227447022b6'
    uri: 'entity:node/248'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -44
    langcode: und
    uuid: 51951a11-ea57-42d3-a7e9-3831ff9b497e
  -
    menu_name: main
    title: 'Our Staff'
    parent: 'menu_link_content:a2bd328e-aa96-49fd-83da-d227447022b6'
    uri: 'entity:node/345'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: und
    uuid: 77585df1-4a50-4096-8de9-71a890ff92d5
  -
    menu_name: main
    title: 'Decade of Centenaries'
    parent: 'menu_link_content:aacca46b-3dea-4531-bab8-3dc8c00ac3ee'
    uri: 'entity:node/220'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: und
    uuid: 58374d64-bb8f-4607-9ce2-1f1585e03fcf
  -
    menu_name: main
    title: 'North Belfast Strategic Good Relations Programme'
    parent: 'menu_link_content:6d849f82-58f7-4dba-9cb5-fc2105b15f96'
    uri: 'entity:node/579'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -44
    langcode: und
    uuid: a566757f-b30d-4b3d-93e8-fdf1a125f72a
  -
    menu_name: main
    title: 'Application Portal'
    parent: 'menu_link_content:6d849f82-58f7-4dba-9cb5-fc2105b15f96'
    uri: 'https://community-relations.flexigrant.com/'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: 3c8d2008-62a7-4d82-be92-1352b496fa22
  -
    menu_name: main
    title: 'Freedom of Information'
    parent: 'menu_link_content:a2bd328e-aa96-49fd-83da-d227447022b6'
    uri: 'entity:node/78'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: und
    uuid: a8f21bd7-46e6-4149-a167-ca4c0eda7bf3
  -
    menu_name: main
    title: Corporate
    parent: 'menu_link_content:a2bd328e-aa96-49fd-83da-d227447022b6'
    uri: 'entity:node/76'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: und
    uuid: 1ef84d0c-f7f1-4e8e-aec9-6cc11e6f35b0
  -
    menu_name: main
    title: 'T:BUC Engagement Forum'
    parent: 'menu_link_content:aacca46b-3dea-4531-bab8-3dc8c00ac3ee'
    uri: 'entity:node/170'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: 992316e4-09c9-402d-9c20-49beabd77894
  -
    menu_name: main
    title: 'Funded Groups Toolkit'
    parent: 'menu_link_content:6d849f82-58f7-4dba-9cb5-fc2105b15f96'
    uri: 'entity:node/798'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -42
    langcode: und
    uuid: bdb4ed8c-7119-42e4-b4cd-46da7a7d9a8c
  -
    menu_name: main
    title: Equality
    parent: 'menu_link_content:a2bd328e-aa96-49fd-83da-d227447022b6'
    uri: 'entity:node/830'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: und
    uuid: df95da56-fff3-4572-aa07-a45857c07f05
  -
    menu_name: main
    title: 'Complaints Procedure'
    parent: 'menu_link_content:a2bd328e-aa96-49fd-83da-d227447022b6'
    uri: 'entity:node/832'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: und
    uuid: 1a423ffe-1d3f-4414-9e30-dba7e582ac90
  -
    menu_name: main
    title: Vacancies
    parent: 'menu_link_content:a2bd328e-aa96-49fd-83da-d227447022b6'
    uri: 'entity:node/687'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -43
    langcode: und
    uuid: 5f7823ec-6f8e-4c52-869f-bb5475aa1af1
  -
    menu_name: main
    title: Engagement
    parent: null
    uri: 'entity:node/939'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -44
    langcode: und
    uuid: aacca46b-3dea-4531-bab8-3dc8c00ac3ee
  -
    menu_name: main
    title: 'Board members'
    parent: 'menu_link_content:a2bd328e-aa96-49fd-83da-d227447022b6'
    uri: 'entity:node/949'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: und
    uuid: acecfb5a-501b-49c6-a874-1643793db4f1
  -
    menu_name: main
    title: 'Good Relations Week'
    parent: 'menu_link_content:aacca46b-3dea-4531-bab8-3dc8c00ac3ee'
    uri: 'entity:node/799'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: und
    uuid: 6b7f669c-bdd3-47dd-906b-b9447a938c18
  -
    menu_name: main
    title: 'Funding Map'
    parent: 'menu_link_content:6d849f82-58f7-4dba-9cb5-fc2105b15f96'
    uri: 'entity:node/1252'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: und
    uuid: b2dbf86a-ca1d-4b1f-8eb0-448e6bb96ec2
  -
    menu_name: main
    title: 'Shared Learning Forum'
    parent: 'menu_link_content:aacca46b-3dea-4531-bab8-3dc8c00ac3ee'
    uri: 'entity:node/1274'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: und
    uuid: c889a02b-3d2f-4705-9ad9-957070488e0c
  -
    menu_name: main
    title: 'CR/CD Small Grants'
    parent: 'menu_link_content:6d849f82-58f7-4dba-9cb5-fc2105b15f96'
    uri: 'entity:node/1476'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: en
    uuid: a37d0a15-f728-4361-8f0a-10137d8da00f
  -
    menu_name: main
    title: 'Core Funding Scheme'
    parent: 'menu_link_content:6d849f82-58f7-4dba-9cb5-fc2105b15f96'
    uri: 'entity:node/87'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: en
    uuid: 8282d8d3-bbb3-40e3-8901-6238fe880cfa
  -
    menu_name: main
    title: 'Media Grant Scheme'
    parent: 'menu_link_content:6d849f82-58f7-4dba-9cb5-fc2105b15f96'
    uri: 'entity:node/88'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: en
    uuid: 9637f22a-dca9-4c0e-ae9d-169a90e9a4c1
  -
    menu_name: main
    title: 'Publications Grant Scheme'
    parent: 'menu_link_content:6d849f82-58f7-4dba-9cb5-fc2105b15f96'
    uri: 'entity:node/847'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -43
    langcode: en
    uuid: 0fd82276-949c-4b48-a047-ad6661f55de2
  -
    menu_name: main
    title: Resources
    parent: null
    uri: 'internal:/Publications'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -39
    langcode: en
    uuid: 16bc81a9-2a4c-49a3-bd72-7d1249df5530
  -
    menu_name: main
    title: 'eNews & eBulletin'
    parent: 'menu_link_content:16bc81a9-2a4c-49a3-bd72-7d1249df5530'
    uri: 'internal:/news'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: en
    uuid: d87d84ff-47b6-42b6-a6bc-9d3df25df60e
  -
    menu_name: main
    title: Publications
    parent: 'menu_link_content:16bc81a9-2a4c-49a3-bd72-7d1249df5530'
    uri: 'internal:/publications'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: en
    uuid: 02817baa-d61a-4585-83ed-9fb9d46356cf
  -
    menu_name: main
    title: 'About Us'
    parent: null
    uri: 'entity:node/1'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: en
    uuid: a2bd328e-aa96-49fd-83da-d227447022b6
  -
    menu_name: main
    title: 'Shared Space'
    parent: 'menu_link_content:16bc81a9-2a4c-49a3-bd72-7d1249df5530'
    uri: 'entity:node/193'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: 6651e011-6f75-473e-995d-be6132b462fd
  -
    menu_name: main
    title: 'CRC Board Minutes'
    parent: 'menu_link_content:16bc81a9-2a4c-49a3-bd72-7d1249df5530'
    uri: 'entity:node/217'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: c608ddb1-42bb-40f3-92c9-b4cb0ea1f967
  -
    menu_name: main
    title: 'Northern Ireland Peace Monitoring Report'
    parent: 'menu_link_content:16bc81a9-2a4c-49a3-bd72-7d1249df5530'
    uri: 'entity:node/188'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: 213fe630-4bbd-4776-a96f-9e28ddcd3c52
  -
    menu_name: main
    title: 'Funding Map Archive'
    parent: 'menu_link_content:6d849f82-58f7-4dba-9cb5-fc2105b15f96'
    uri: 'internal:/funding-map-archive'
    link_title: ''
    description: null
    enabled: true
    expanded: true
    weight: -46
    langcode: en
    uuid: 1e27f577-473c-4aa8-9411-abd8fc2ae52c
