_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
name: 'Community Relations Council'
mail: Test@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
uuid: 2561f1b4-e495-4bc8-b802-9f9f12cfa418
frontpage_title: 'Welcome to Drupal site'
