features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
ga_tracking_disabled: 1
ga_tracking_disabled_eu: 0
twitter_profile_url: 'https://twitter.com/PBNINews'
facebook_profile_url: ''
linkedin_profile_url: 'https://www.linkedin.com/company/probation-board-for-northern-ireland'
pinterest_profile_url: ''
youtube_profile_url: 'https://www.youtube.com/ProbationBoardNI'
instagram_profile_url: 'https://www.instagram.com/pbni.news/'
