_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 5ee22ef9-824e-47b5-987a-77359ab97775
name: 'Probation Board for Northern Ireland'
mail: eddwebdev@finance-ni.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Drupal the Probation Board for Northern Ireland'
frontpage_show_title: 0
