adding:
  backend_config:
    connector_config:
      host: solr
      port: 8983
      core: nicybersecuritycentre
      skip_schema_check: true
      solr_install_dir: /opt/solr
      checkpoints_collection: ''
      stats_cache: org.apache.solr.search.stats.LRUStatsCache
      distrib: true
      context: solr
      username: solr
      password: SolrRocks
removing:
  backend_config:
    connector_config:
      host: nicybersecuritycentre_solr.internal
      port: 8080
      core: nicybersecuritycentre_index
      skip_schema_check: false
      solr_install_dir: ''
