application_name: 'Unity 1'
application_id: '6tlkpwbr6tndk'
sites:
  'uregni':
    name: 'Utility Regulator for Northern Ireland'
    url: 'uregni.gov.uk'
    database: "uregni"
    solr: 'uregni'
    cron_spec: '10 * * * *'
    cron_cmd: 'cd web/sites/nifiscalcouncil ; drush core-cron'
  'odscni':
    name: 'The Office of the Discretionary Support Commissioner'
    url: 'odscni.org.uk'
    database: "odscni"
    solr: ''
    cron_spec: '10 * * * *'
    cron_cmd: 'cd web/sites/odscni ; drush core-cron'