project_name: 'Unity Svr 2'
project_id: kamkoebtv74zm
sites:
    mentalhealthchampionni:
        name: 'Mental Health Champion for Northern Ireland'
        url: mentalhealthchampion-ni.org.uk
        solr: mentalhealthchampionni
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/mentalhealthchampionni ; drush core-cron'
        database: mentalhealthchampionni
        deploy: false
