project_name: 'Unity Svr 2'
project_id: kamkoebtv74zm
sites:
    mentalhealthchampionni:
        name: 'Mental Health Champion'
        url: mentalhealthchampion-ni.org.uk
        solr: mentalhealthchampionni
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/mentalhealthchampionni ; drush core-cron'
        database: mentalhealthchampionni
        deploy: true
    imtac:
        name: imtac
        url: imtac.org.uk
        solr: imtac
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/imtac ; drush core-cron'
        database: imtac
        deploy: true
