project_name: 'Unity Svr 2'
project_id: kamkoebtv74zm
sites:
    mentalhealthchampionni:
        name: 'Mental Health Champion for Northern Ireland'
        url: mentalhealthchampion-ni.org.uk
        solr: mentalhealthchampionni
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/mentalhealthchampionni ; drush core-cron'
        database: mentalhealthchampionni
        deploy: false
    publicappointmentsni:
        name: 'The Commissioner for Public Appointments for Northern Ireland'
        url: publicappointmentsni.org
        solr: publicappointmentsni
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/publicappointmentsni ; drush core-cron'
        database: publicappointmentsni
        deploy: false
    ircommission:
        name: 'Independent Reporting Commission'
        url: ircommission.org
        solr: ircommission
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/ircommission ; drush core-cron'
        database: ircommission
        deploy: false
