_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: f57d644a-cfe2-45d8-ba9e-4ed31e74d17b
name: 'Sentence Review Commissioners'
mail: admin@src.org.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/79
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to The Sentence Review Commissioners in Northern Ireland'
frontpage_show_title: 1
