_core:
  default_config_hash: 9igS-9qqxUg14iAlnst2AcWBhvahm0EE5E9EzflfTpM
first_day: 1
country:
  default: GB
timezone:
  default: Europe/London
  user:
    configurable: false
    default: 0
    warn: false
