_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 634ccd18-d4be-407f-b94b-7a40dd534a5c
name: 'Unity 2 Test'
mail: me@stevecousins.co.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Drupal site'
frontpage_show_title: 0
