_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 569c8fd6-907b-4b87-85a5-15f03e398b03
name: 'The Commissioner for Public Appointments for Northern Ireland'
mail: info@publicappointmentsni.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to the website of the Commissioner for Public Appointments for Northern Ireland'
frontpage_show_title: 1
