adding:
  backend_config:
    connector_config:
      host: solr
      port: 8983
      core: publicappointmentsni
      skip_schema_check: true
      solr_install_dir: /opt/solr
    index_empty_text_fields: false
    suppress_missing_languages: false
removing:
  backend_config:
    connector_config:
      host: publicappointmentsni_solr.intranet
      port: 8080
      core: publicappointmentsni_index
      skip_schema_check: false
      solr_install_dir: ''
