<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_alter().
 */
function judiciaryni_common_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_judicial_member_form' || $form_id == 'node_judicial_member_edit_form') {
    $form['title']['#disabled'] = 'disabled';
    $form['title']['widget'][0]['value']['#description'] = t('You cannot edit this field. It is created automatically using the Name of Judge and Judicial Tier.');

  }
}


/**
 * Implements hook_entity_presave().
 */
function judiciaryni_common_entity_presave(EntityInterface $entity) {
  // This will fire when nodes are created or edited.
  if ($entity instanceof NodeInterface && $entity->bundle() === 'judicial_member') {

    $judgeName = $entity->get('field_surname')->value;
    $judgeSex = $entity->get('field_sex_of_member')->value;
    $tierTID = $entity->get('field_judicial_tier')->target_id;
    $judgeTitle = $entity->get('field_prefix_title')->value;
    $shorttitle = $judgeTitle . ' ' . $judgeName;

    if ($tierTID !== NULL) {
      $tier = Term::load($tierTID);
      $tierName = $tier->getName();

      if ($judgeTitle == 'Vacant') {
        $shorttitle = $judgeName . ' ' . $tierName;
      }
      elseif ($tierName == 'Lord Chief Justice' || $tierName == 'Lady Chief Justice') {
        $shorttitle = $judgeName . ' LCJ';
      }
      elseif ($tierName == 'Justice of Appeal') {
        $shorttitle = $judgeName . ' LJ';
      }
      elseif ($tierName == 'High Court Judge') {
        $shorttitle = $judgeName . ' J';
      }
      elseif ($tierName == 'County Court Judge' || $tierName == 'Recorder of Belfast' || $tierName == 'Recorder of Londonderry') {
        $sex = 'His ';
        if ($judgeSex !== 'male') {
          $sex = 'Her ';
        }
        $shorttitle = $sex . 'Honour Judge ' . $judgeName;
      }
      elseif ($tierName == 'Master of the High Court') {
        $shorttitle = 'Master ' . $judgeName;
      }
      elseif ($tierName == 'District Judge') {
        $shorttitle = 'District Judge ' . $judgeName;
      }
      elseif ($tierName == 'District Judge (Magistrates’ Courts)' || $tierName == 'Presiding District Judge (Magistrates’ Courts)') {
        $shorttitle = 'District Judge (MC) ' . $judgeName;
      }

    }

    $entity->setTitle($shorttitle);
  }
}
