'https://www.www.pbni.org.uk/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://www.pbni.org.uk/':
    type: redirect
    to: 'https://www.www.pbni.org.uk/'
'https://www.{all}/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://{all}/':
    type: redirect
    to: 'https://www.{all}/'
