#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
'https://www.mentalhealthchampion-ni.org.uk.{default}/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://mentalhealthchampion-ni.org.uk.{default}/':
    type: redirect
    to: 'https://www.mentalhealthchampion-ni.org.uk.{default}/'
'https://www.ircommission.org/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://ircommission.org/':
    type: redirect
    to: 'https://www.ircommission.org/'
'https://www.nicertoffice.org.uk/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://nicertoffice.org.uk/':
    type: redirect
    to: 'https://www.nicertoffice.org.uk/'
'https://www.victimspaymentsboard.org.uk/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://victimspaymentsboard.org.uk/':
    type: redirect
    to: 'https://www.victimspaymentsboard.org.uk/'
'https://www.hiaredressni.uk/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://hiaredressni.uk/':
    type: redirect
    to: 'https://www.hiaredressni.uk/'
'https://www.nijac.gov.uk/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://nijac.gov.uk/':
    type: redirect
    to: 'https://www.nijac.gov.uk/'
'https://www.community-relations.org.uk/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://community-relations.org.uk/':
    type: redirect
    to: 'https://www.community-relations.org.uk/'
'https://www.sentencereview.org.uk/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://sentencereview.org.uk/':
    type: redirect
    to: 'https://www.sentencereview.org.uk/'
'https://www.nicybersecuritycentre.gov.uk/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://nicybersecuritycentre.gov.uk/':
    type: redirect
    to: 'https://www.nicybersecuritycentre.gov.uk/'
'https://www.ppsni.gov.uk/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://ppsni.gov.uk/':
    type: redirect
    to: 'https://www.ppsni.gov.uk/'
'https://www.pacni.gov.uk/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://pacni.gov.uk/':
    type: redirect
    to: 'https://www.pacni.gov.uk/'
'https://www.{all}/':
    type: upstream
    upstream: 'unity_svr_2:http'
    cache:
        enabled: 'false'
'https://{all}/':
    type: redirect
    to: 'https://www.{all}/'
