#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
'https://www.mentalhealthchampion-ni.org.uk.{default}/':
    type: upstream
    upstream: 'unity.svr.2:http'
    cache:
        enabled: 'false'
'https://mentalhealthchampion-ni.org.uk.{default}/':
    type: redirect
    to: 'https://www.mentalhealthchampion-ni.org.uk.{default}/'
'https://www.{all}/':
    type: upstream
    upstream: 'unity.svr.2:http'
    cache:
        enabled: 'false'
'https://{all}/':
    type: redirect
    to: 'https://www.{all}/'
