db:
    type: 'mariadb:10.4'
    disk: 40960
    configuration:
        schemas:
            - mentalhealthchampionni
            - imtac
        endpoints:
            mentalhealthchampionni:
                default_schema: mentalhealthchampionnidb
                privileges:
                    mentalhealthchampionnidb: admin
            imtac:
                default_schema: imtacdb
                privileges:
                    imtacdb: admin
solr:
    type: 'solr:7.7'
    disk: 1024
    configuration:
        cores:
            mentalhealthchampionni_index:
                conf_dir: !archive solr_config/
            imtac_index:
                conf_dir: !archive solr_config/
        endpoints:
            mentalhealthchampionni:
                core: mentalhealthchampionni_index
            imtac:
                core: imtac_index
redis:
    type: 'redis:6.0'
