db:
    type: 'mariadb:10.4'
    disk: 5000
    configuration:
        schemas:
            - mentalhealthchampiondb
            - pbnidb
        endpoints:
            mentalhealthchampion:
                default_schema: mentalhealthchampiondb
                privileges:
                    mentalhealthchampiondb: admin
            pbni:
                default_schema: pbnidb
                privileges:
                    pbnidb: admin
redis:
    type: 'redis:6.0'
