db:
    type: 'mariadb:10.4'
    disk: 4000
    configuration:
        schemas:
            - mentalhealthchampionnidb
            - publicappointmentsnidb
        endpoints:
            mentalhealthchampionni:
                default_schema: mentalhealthchampionnidb
                privileges:
                    mentalhealthchampionnidb: admin
            publicappointmentsni:
                default_schema: publicappointmentsnidb
                privileges:
                    publicappointmentsnidb: admin
solr:
    type: 'solr:7.7'
    disk: 1024
    configuration:
        cores:
            mentalhealthchampionni_index:
                conf_dir: !archive solr_config/
            publicappointmentsni_index:
                conf_dir: !archive solr_config/
        endpoints:
            mentalhealthchampionni:
                core: mentalhealthchampionni_index
            publicappointmentsni:
                core: publicappointmentsni_index
redis:
    type: 'redis:6.0'
