db:
    type: 'mariadb:10.4'
    disk: 40960
    configuration:
        schemas:
            - mentalhealthchampion
        endpoints:
            mentalhealthchampion:
                default_schema: mentalhealthchampiondb
                privileges:
                    mentalhealthchampiondb: admin
redis:
    type: 'redis:6.0'
