db:
    type: 'mariadb:10.4'
    disk: 4000
    configuration:
        schemas:
            - mentalhealthchampionnidb
            - unity2testdb
        endpoints:
            mentalhealthchampionni:
                default_schema: mentalhealthchampionnidb
                privileges:
                    mentalhealthchampionnidb: admin
            unity2test:
                default_schema: unity2testdb
                privileges:
                    unity2testdb: admin
redis:
    type: 'redis:6.0'
