#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
db:
    type: 'mariadb:10.4'
    disk: 4000
    configuration:
        schemas:
            - mentalhealthchampionnidb
            - publicappointmentsnidb
            - ircommissiondb
            - imtacdb
            - nicertofficedb
            - victimspaymentsboarddb
            - hiaredressnidb
            - cvocnidb
            - nijacdb
            - crcdb
            - sentencereviewdb
            - srcdb
            - communityrelationsdb
        endpoints:
            mentalhealthchampionni:
                default_schema: mentalhealthchampionnidb
                privileges:
                    mentalhealthchampionnidb: admin
            publicappointmentsni:
                default_schema: publicappointmentsnidb
                privileges:
                    publicappointmentsnidb: admin
            ircommission:
                default_schema: ircommissiondb
                privileges:
                    ircommissiondb: admin
            imtac:
                default_schema: imtacdb
                privileges:
                    imtacdb: admin
            nicertoffice:
                default_schema: nicertofficedb
                privileges:
                    nicertofficedb: admin
            victimspaymentsboard:
                default_schema: victimspaymentsboarddb
                privileges:
                    victimspaymentsboarddb: admin
            hiaredressni:
                default_schema: hiaredressnidb
                privileges:
                    hiaredressnidb: admin
            cvocni:
                default_schema: cvocnidb
                privileges:
                    cvocnidb: admin
            nijac:
                default_schema: nijacdb
                privileges:
                    nijacdb: admin
            crc:
                default_schema: crcdb
                privileges:
                    crcdb: admin
            sentencereview:
                default_schema: sentencereviewdb
                privileges:
                    sentencereviewdb: admin
            src:
                default_schema: srcdb
                privileges:
                    srcdb: admin
            communityrelations:
                default_schema: communityrelationsdb
                privileges:
                    communityrelationsdb: admin
solr:
    type: 'solr:7.7'
    disk: 1024
    configuration:
        cores:
            mentalhealthchampionni_index:
                conf_dir: !archive solr_config/
            publicappointmentsni_index:
                conf_dir: !archive solr_config/
            ircommission_index:
                conf_dir: !archive solr_config/
            imtac_index:
                conf_dir: !archive solr_config/
            nicertoffice_index:
                conf_dir: !archive solr_config/
            victimspaymentsboard_index:
                conf_dir: !archive solr_config/
            hiaredressni_index:
                conf_dir: !archive solr_config/
            cvocni_index:
                conf_dir: !archive solr_config/
            nijac_index:
                conf_dir: !archive solr_config/
            crc_index:
            src_index:
                conf_dir: !archive solr_config/
            communityrelations_index:
                conf_dir: !archive solr_config/
            sentencereview_index:
                conf_dir: !archive solr_config/
        endpoints:
            mentalhealthchampionni:
                core: mentalhealthchampionni_index
            publicappointmentsni:
                core: publicappointmentsni_index
            ircommission:
                core: ircommission_index
            imtac:
                core: imtac_index
            nicertoffice:
                core: nicertoffice_index
            victimspaymentsboard:
                core: victimspaymentsboard_index
            hiaredressni:
                core: hiaredressni_index
            cvocni:
                core: cvocni_index
            nijac:
                core: nijac_index
            crc:
                core: crc_index
            sentencereview:
                core: sentencereview_index
            src:
                core: src_index
            communityrelations:
                core: communityrelations_index
redis:
    type: 'redis:6.0'
