db:
    type: 'mariadb:10.4'
    disk: 4000
    configuration:
        schemas:
            - mentalhealthchampiondb
        endpoints:
            mentalhealthchampion:
                default_schema: mentalhealthchampiondb
                privileges:
                    mentalhealthchampiondb: admin
redis:
    type: 'redis:6.0'
