_core:
  default_config_hash: 2TnP0TViNExHGuA7Cdr4L3uxhYGNzKyL0XnoAhtSHMQ
form_ids:
  - 'comment_*'
  - user_login_form
  - user_pass
  - user_register_form
  - 'contact_*'
  - 'webform_submission_*'
show_form_ids: false
