features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: sites/imtac/themes/imtac_theme/logo.svg
favicon:
  use_default: 1
twitter_profile_url: ''
facebook_profile_url: ''
linkedin_profile_url: ''
pinterest_profile_url: ''
youtube_profile_url: ''
instagram_profile_url: ''
