features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
basic_page_structure: 1
twitter_profile_url: 'https://twitter.com/nijacnews'
facebook_profile_url: ''
linkedin_profile_url: 'https://www.linkedin.com/company/northern-ireland-judicial-appointments-commission?original_referer=https%3A%2F%2Fwww.nijac.gov.'
pinterest_profile_url: ''
youtube_profile_url: 'https://www.youtube.com/channel/UCVAXdKieIY6yBH8NlG8GgWA'
instagram_profile_url: ''
