<?php

/**
 * @file
 * Contains uregni_breadcrumbs.module.
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_system_breadcrumb_alter().
 *
 * Altering the search view page breadcrumbs, when facets are selected the breadcrumb trail is overwritten.
 */
function uregni_breadcrumbs_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $links = $breadcrumb->getLinks();
  $route_name = $route_match->getRouteName();

  // The publications view page has an extra breadcrumb linked to the about us page so we need to add this in to keep the existing structure.
  if ($route_name == 'view.publications_search.publication_search_page') {
    $about_us_link[] = Link::fromTextandUrl(t('About us'), Url::fromUri('internal:/about-us'));
    array_splice($links, 1, 0, $about_us_link);
  }

  // Loop through the links for links that have facet queries added to them and unset the link of the last breadcrumb.
  // The facets module breadcrumb links them all by default.
  foreach ($links as $link) {
    // Strip the - search results text from the page title breadcrumb link.
    if (preg_match('/([A-Z|a-z]+) - search results/', $link->getText(), $matches)) {
      $link->setText($matches[1]);
    }

    $params = $link->getUrl()->getRouteParameters();
    if (!empty($params['facets_query'])) {
      // Remove link from the last breadcrumb link.
      end($links)->setUrl(Url::fromRoute('<none>'));
      $breadcrumb = new Breadcrumb();
      $breadcrumb->setLinks($links);
      $breadcrumb->addCacheContexts(['url.path']);
    }
  }
}
