_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: af095fd6-a277-4ad3-8c9d-3fee3143a071
name: 'Mental Health Champion Northern Ireland'
mail: test@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: Welcome
frontpage_show_title: 1
