#!/usr/bin/env bash

## Description: Execute local PHPCS static analysis checks in the current directory and non contrib modules and themes.
## Usage: phpcs
## Example: "ddev phpcs"
## HostWorkingDir: true

/var/www/html/phpcs.sh ./ "/var/www/html" "/var/www/html/web/modules/origins /var/www/html/web/modules/custom /var/www/html/web/themes/custom"
