<?php

/**
 * @file
 * Functions to support theming in the odscni_theme theme.
 */

/**
 * Implements hook_preprocess_html().
 */
function odscni_theme_preprocess_html(&$variables) {
  if (!empty($variables['node_type'])) {
    if ($variables['node_type'] == 'page') {
      $variables['attributes']['class'][] = 'one-sidebar';
      $variables['attributes']['class'][] = 'sidebar-second';
    }
  }
}
