adding:
  backend_config:
    connector_config:
      host: solr
      port: 8983
      core: ppsni
      skip_schema_check: true
      solr_install_dir: /opt/solr
    index_empty_text_fields: false
    suppress_missing_languages: false
removing:
  backend_config:
    connector_config:
      host: ppsni_solr.intranet
      port: 8080
      core: ppsni_index
      skip_schema_check: false
      solr_install_dir: ''
