_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: ca323cde-7c67-4b08-ad08-018bd791ef23
name: 'Industrial Court'
mail: enquiries@industrialcourt.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: Welcome
frontpage_show_title: 1
