_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
name: 'Industrial Court'
mail: enquiries@industrialcourt.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
uuid: ca323cde-7c67-4b08-ad08-018bd791ef23
frontpage_title: 'Welcome to Drupal site'
